# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
 branches:
   include:
     - dev

pool:
  vmImage: 'windows-2019'

steps:
- task: MSBuild@1
  displayName: "Build Database Project"
  inputs:
    solution: 'Athena-DDLAutomationDemo/Athena-DDLAutomation/Athena-DDLAutomation.sqlproj'

- task: CopyFiles@2
  inputs:
    Contents: |
      Athena-DDLAutomationDemo\Athena-DDLAutomation\bin\Debug\**
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Scripts'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Scripts'
    ArtifactName: Dacpac
    ArtifactType: Container



