# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- task: MSBuild@1
  displayName: "Build Database Project"
  inputs:
    solution: 'Athena-DDLAutomationDemo/Athena-DDLAutomation/Athena-DDLAutomation.sqlproj'

- task: CopyFiles@2
  inputs:
    Contents: |
      Athena-DDLAutomationDemo\Athena-DDLAutomation\bin\Debug\**\*.sql
      Athena-DDLAutomationDemo\Athena-DDLAutomation\bin\Debug\Athena-DDLAutomation.dacpac
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Dacpac
    ArtifactType: Container



