IF OBJECT_ID('ATHENA_DW.CARRIER_DIM_NEW','U') IS NOT NULL 
	DROP TABLE ATHENA_DW.CARRIER_DIM_NEW

CREATE TABLE ATHENA_DW.CARRIER_DIM_NEW
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX
	(
		CARRIER_CODE ASC
	)
) AS
SELECT CARRIER_ID
      ,CARRIER_CODE
      ,CARRIER_DESC
	  ,0 AS CARRIER_XYZ -- If this is a computed column or with IS NULL check, Add ALTER TABLE ATHENA_DW.CARRIER_DIM ALTER COLUMN CARRIER_XYZ INT NOT NULL
      ,INFERRED_IND
      ,INFERRED_RESOLVED_DATE
      ,CREATE_AUDIT_ID
      ,CREATE_DB_TIMESTAMP
      ,UPDATE_AUDIT_ID
      ,UPDATE_DB_TIMESTAMP
  FROM ATHENA_DW.CARRIER_DIM 

RENAME OBJECT ATHENA_DW.CARRIER_DIM TO CARRIER_DIM_OLD;
RENAME OBJECT ATHENA_DW.CARRIER_DIM_NEW TO CARRIER_DIM;

DROP TABLE ATHENA_DW.CARRIER_DIM_OLD;