-- Approach 1 - The issue is the column is added at the end of the table

--ALTER TABLE ATHENA_DW.CHANNEL_DIM ADD CHANNEL_XYZ VARCHAR(10) NULL
--UPDATE ATHENA_DW.CHANNEL_DIM SET CHANNEL_XYZ = 'ABC'
---- OR
---- ALTER TABLE ATHENA_DW.CHANNEL_DIM ADD CHANNEL_XYZ VARCHAR(10) NOT NULL DEFAULT 'ABC'
--GO
--ALTER TABLE ATHENA_DW.CHANNEL_DIM ALTER COLUMN CHANNEL_XYZ VARCHAR(10) NOT NULL
--GO

-- Approach 2 - Create a temporary table with new column

IF OBJECT_ID('ATHENA_DW.CHANNEL_DIM_NEW','U') IS NOT NULL 
	DROP TABLE ATHENA_DW.CHANNEL_DIM_NEW

CREATE TABLE ATHENA_DW.CHANNEL_DIM_NEW
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX
	(
		CHANNEL_CODE ASC
	)
) AS
SELECT CHANNEL_ID
      ,CHANNEL_CODE
      ,CHANNEL_DESC
	  , 0 AS CHANNEL_XYZ -- If this is a computed column or with IS NULL check, Add ALTER TABLE ATHENA_DW.CHANNEL_DIM ALTER COLUMN CHANNEL_XYZ INT NOT NULL
      ,CREATE_AUDIT_ID
      ,CREATE_DB_TIMESTAMP
      ,UPDATE_AUDIT_ID
      ,UPDATE_DB_TIMESTAMP
 FROM ATHENA_DW.CHANNEL_DIM 

RENAME OBJECT ATHENA_DW.CHANNEL_DIM TO CHANNEL_DIM_OLD;
RENAME OBJECT ATHENA_DW.CHANNEL_DIM_NEW TO CHANNEL_DIM;
DROP TABLE ATHENA_DW.CHANNEL_DIM_OLD;

-- 
IF OBJECT_ID('ATHENA_DW.CARRIER_DIM_NEW','U') IS NOT NULL 
	DROP TABLE ATHENA_DW.CARRIER_DIM_NEW

CREATE TABLE ATHENA_DW.CARRIER_DIM_NEW
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX
	(
		CARRIER_CODE ASC
	)
) AS
SELECT CARRIER_ID
      ,CARRIER_CODE
      ,CARRIER_DESC
	  ,0 AS CARRIER_XYZ -- If this is a computed column or with IS NULL check, Add ALTER TABLE ATHENA_DW.CARRIER_DIM ALTER COLUMN CARRIER_XYZ INT NOT NULL
      ,INFERRED_IND
      ,INFERRED_RESOLVED_DATE
      ,CREATE_AUDIT_ID
      ,CREATE_DB_TIMESTAMP
      ,UPDATE_AUDIT_ID
      ,UPDATE_DB_TIMESTAMP
  FROM ATHENA_DW.CARRIER_DIM 

RENAME OBJECT ATHENA_DW.CARRIER_DIM TO CARRIER_DIM_OLD;
RENAME OBJECT ATHENA_DW.CARRIER_DIM_NEW TO CARRIER_DIM;

DROP TABLE ATHENA_DW.CARRIER_DIM_OLD;
