CREATE TABLE ATHENA_DW.BI_ITEM_GROUP (
       USER_NAME                       VARCHAR(10)          NOT NULL 
     , ITEM_GROUP_CODE                 VARCHAR(10)          NOT NULL 
     , ITEM_NUM                        BIGINT              NOT NULL 
     , COMPANY_NUM                     INTEGER              NOT NULL 
     , ITEM_GROUP_DESC                 VARCHAR(60)         
     , COMPANY_CODE                    VARCHAR(10)         
     , COMPANY_NAME                    VARCHAR(60)         
     , CREATE_AUDIT_ID                 BIGINT              
     , CREATE_DB_TIMESTAMP             DATETIME2(6)        
) 
 WITH 
 ( DISTRIBUTION = REPLICATE
 , HEAP 
 )
;
GO

CREATE CLUSTERED COLUMNSTORE INDEX IX_ITMGRP_CCI ON ATHENA_DW.BI_ITEM_GROUP
 WITH (DROP_EXISTING = OFF);

GO

ALTER TABLE ATHENA_DW.BI_ITEM_GROUP ADD CONSTRAINT ITMGRP_PK PRIMARY KEY NONCLUSTERED (ITEM_NUM,COMPANY_NUM,ITEM_GROUP_CODE,USER_NAME) NOT ENFORCED; 
GO
