CREATE TABLE [ATHENA_DW].[CHANNEL_DIM]
(
	[CHANNEL_ID] [bigint] NOT NULL,
	[CHANNEL_CODE] [varchar](20) NOT NULL,
	[CHANNEL_DESC] [varchar](60) NOT NULL,
	[CHANNEL_XYZ] INT NOT NULL,
	[CREATE_AUDIT_ID] [bigint] NOT NULL,
	[CREATE_DB_TIMESTAMP] [datetime2](6) NOT NULL,
	[UPDATE_AUDIT_ID] [bigint] NOT NULL,
	[UPDATE_DB_TIMESTAMP] [datetime2](6) NOT NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX
	(
		[CHANNEL_CODE] ASC
	)
)
GO 