CREATE TABLE [ATHENA_DW].[COUPON_DIM]
(
	[COUPON_ID] [bigint] IDENTITY(10000000000,1) NOT NULL,
	[COUPON_NUM] [int] NOT NULL,
	[COMPANY_NUM] [int] NOT NULL,
	[COUPON_DESC] [varchar](270) NOT NULL,
	[COUPON_BARCODE_NUM] [decimal](15, 0) NOT NULL,
	[SOURCE_SYSTEM] [varchar](10) NOT NULL,
	[INFERRED_IND] [smallint] NOT NULL,
	[INFERRED_RESOLVED_DATE] [date] NULL,
	[CREATE_AUDIT_ID] [bigint] NOT NULL,
	[CREATE_DB_TIMESTAMP] [datetime2](6) NOT NULL,
	[UPDATE_AUDIT_ID] [bigint] NOT NULL,
	[UPDATE_DB_TIMESTAMP] [datetime2](6) NOT NULL,
 CONSTRAINT [CPNDIM_PK] PRIMARY KEY NONCLUSTERED 
	(
		[COUPON_ID] ASC
	) NOT ENFORCED ,
 CONSTRAINT [CPNDIM_UN] UNIQUE NONCLUSTERED 
	(
		[COUPON_NUM] ASC,
		[COMPANY_NUM] ASC
	) NOT ENFORCED 
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX
	(
		[COUPON_NUM] ASC,
		[COMPANY_NUM] ASC
	)
)
GO

ALTER TABLE [ATHENA_DW].[COUPON_DIM] ADD  DEFAULT ((0)) FOR [INFERRED_IND]
GO